name: Build and push prod

on:
   release:
    types: [published]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./Dockerfile.prod
          tags: natin56y/mizipets-front:latest
      
      - name: ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          port: 22
          script: |
            cd mizipets-api
            docker compose -f docker-compose.prod.yml stop front
            docker compose -f docker-compose.prod.yml pull front
            docker compose -f docker-compose.prod.yml up -d front