name: Build and push staging

on: 
  workflow_dispatch:
    branches: ['staging']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./Dockerfile.staging
          tags: natin56y/mizipets-front-staging:latest
      
      - name: ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_KEY }}
          port: 22
          script: |
            cd mizipets-api
            docker compose -f docker-compose.staging.yml stop front
            docker compose -f docker-compose.staging.yml pull front
            docker compose -f docker-compose.staging.yml up -d front